### ISSUE TITLE
Document how to enable keep-alive for websockets

### ISSUE THREAD

**Issue by kshpytsya** [fanout/django-grip#12]
It is unclear whether `set_hold_stream` is applicable to WebSockets.
I am trying to enable keep-alives for a WebSocket by doing this:

```py
django_grip.set_hold_stream(request, [], keep_alive_timeout=30, keep_alive_data="somestring")
```

In Pushpin log (running at `--log-level 10`), I see no relevant mentions of keep-alives (there are some apparently unrelated keep-alives with ttl of 60).

I use `wscat` CLI client for testing, and no keep-alive messages (I would expect "somestring") arrive there, and also the WebSocket itself gets terminated in 50s (which is the timeout configured in HAProxy, behind which Pushpin runs).

I plan to run packet capture of traffic between django app and pushpin tomorrow.

**Comment by jkarneges** [comment]
The `set_hold_stream` method is for HTTP streaming. It is not applicable to WebSockets.

To enable keep alives on a WebSocket, send a `keep-alive` control message. Here's how to do that using a `WebSocketContext` object:

```py
from gripcontrol import websocket_control_message

ws.send_control(websocket_control_message('keep-alive', {'content': 'somestring', 'timeout': 30}))
```

More info: https://pushpin.org/docs/advanced/#keep-alives

**Comment by kshpytsya** [comment]
Thank you for your prompt reply. Your code works for me.
