### ISSUE TITLE
Setting up wscontext.meta OR wscontext.orig_meta causes an error. 

### ISSUE THREAD

**Issue by dmytro-cherkaskyy** [fanout/django-grip#13]
Seems to be 2 errors on lines 

- https://github.com/fanout/django-grip/blob/58298ba1dc3d687719763e1bcab1bd3bda32f089/django_grip.py#L321
https://github.com/fanout/django-grip/blob/58298ba1dc3d687719763e1bcab1bd3bda32f089/django_grip.py#L333

I suppose that `wscontext.meta` and `wscontext.orig_meta` are dictionaries. 
Iterating over it should be done using `six.iteritems(wscontext.meta)` or `wscontext.meta.items()`

Otherwise now I'm getting the error `Error: too many values to unpack`

**Comment by jkarneges** [comment]
Thanks for reporting this! Fixed in ef31dc8a2b7a87f0f788fdab3575f8a824e59304
