### ISSUE TITLE
Werkzeug incompatibility

### ISSUE THREAD

**Issue by louisrigot** [fanout/django-grip#15]
I'm trying to use `django-grip` (as a dependency of [django-eventstream](https://github.com/fanout/django-eventstream)) in the same project as `tensorflow` (which indirectly depends on `Werkzeug>=1.0.1`. I've taken a look at the code and the newer versions of Werkzeug should be compatible up to Werkzeug 2.10, at which point the "The `multiple` parameter of `parse_options_header` is deprecated.".

https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

Would it be possible to change setup.py to specify `Werkzeug<2.1` instead of the current `Werkzeug<1`? I can submit a PR if you prefer.

Thanks!

**Comment by jkarneges** [comment]
Seems reasonable! I've published 3.1.0 with the change.
