### ISSUE TITLE
[BUG] Breaking changes from urllib3 version 2.0.0 above.

### ISSUE THREAD

**Issue by jpmateo022** [fanout/django-grip#17]
it seems that newer versions of urllib3 will break the library as it uses `method_whitelist` which is removed in version 2.0.0 and above of urllib3

```
got an unexpected keyword argument 'method_whitelist'
```

Workaround was to use lower version 1.27 below of urllib3.

**Comment by jkarneges** [comment]
Thanks for the report! Released version 3.4.0 of pubcontrol with a fix.
