### ISSUE TITLE
Security vulnerabilities [High & Medium Severity]  in werkzeug@2.3.7  introduced by django-grip@3.4.0 dependency

### ISSUE THREAD

**Issue by montaro** [fanout/django-grip#19]
There are two vulnerabilities reported by Snyk in `werkzeug@2.3.7` which is an indirect dependency in my case because `django-grip@3.4.0` requires it.

I've checked the Werkzeug [releases](https://pypi.org/project/Werkzeug/#history), and it is the last release in the `2.*.*` before the `3.*.*` started. The fix is in the version `3.0.1`.
 
 Apparently, the `django-grip` setup.py file explicitly specifies that the required version of Werkzeug should be < version `3.*` (`'Werkzeug>=1.0,<3'`)
```
Pin werkzeug@2.3.7 to werkzeug@3.0.1 to fix
  ✗ Inefficient Algorithmic Complexity (new) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-WERKZEUG-6035177] in werkzeug@2.3.7
    introduced by django-eventstream@4.5.1 > django-grip@3.4.0 > werkzeug@2.3.7
  ✗ Denial of Service (DoS) (new) [High Severity][https://security.snyk.io/vuln/SNYK-PYTHON-WERKZEUG-6041510] in werkzeug@2.3.7
    introduced by django-eventstream@4.5.1 > django-grip@3.4.0 > werkzeug@2.3.7
```

Is `django-grip` ready to update the Werkzeug dependency to `3.0.1`?

**Comment by jkarneges** [comment]
Thanks for this, it turns out the code is compatible with Werkzeug 3 so I've updated the accepted version.
