### ISSUE TITLE
Documentation and sample usage is confusing

### ISSUE THREAD

**Issue by LihengGong** [fanout/django-grip#9]
Sample usage is confusing

I'm trying to use pushpin in my app. I use websocket(instead of HTTP streaming) as transports.

But the README and the documentation is quite confusing(allow me to use such harsh words).

I have several questions:

1. ~~In your README, what is the two code snippets in 'Example view:' supposed to run against? Are they supposed to run in Django? If so, what directory should they be placed into?~~
I managed to figure out the set up.

2. I noticed that your documentation(https://pushpin.org/docs/usage/#transports) mentioned that "WebSocket-over-HTTP" should be preferred.
   My question is: If websocket is mocked by HTTP, then why bother using websocket at all(I mean, why not using pure HTTP instead)? I do not get the rational of it.

3. Do you have a front end plus backend demo for websocket + pushpin?

4. I noticed that in you code, only HTTP request method 'POST' is processed(e.g. https://github.com/fanout/headline/blob/master/headlineapp/views.py). From my understanding, it seems that you discourage HTTP request method 'GET'. If so, how should the backend respond to such a client request below?

```javascript
var chatSocket = new WebSocket(
      'ws://' + window.location.host +
      '/ws/chat/' + roomName + '/');
```

From my understanding, the above code sends an HTTP request 'GET'(see below), but it seems that 'GET' is discouraged, which is quite confusing to me.(I combed through your documentation but it is not addressed in your documentation. And honestly, your documentation is too brief to be friendly to newcomers of your product(sorry to be so blunt)).

```
GET /ws/chat/aaaa/ HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET /ws/chat/aaaa/ HTTP/1.1\r\n]
            [GET /ws/chat/aaaa/ HTTP/1.1\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: GET
        Request URI: /ws/chat/aaaa/
        Request Version: HTTP/1.1
    Host: localhost:8000\r\n
    Connection: Upgrade\r\n
    Pragma: no-cache\r\n
    Cache-Control: no-cache\r\n
    Upgrade: websocket\r\n
    Origin: http://localhost:8000\r\n
    Sec-WebSocket-Version: 13\r\n
```

**Comment by jkarneges** [comment]
Hi,

Thanks for the feedback about the docs.

To answer your remaining questions:

2) This is a matter of API taste. You could use WebSocket for server->client data push only, and normal HTTP from the client for the rest of your communication (request/response). However, some client developers might consider a bidirectional WebSocket API more convenient to use. It's really up to you. Note that even if your WebSocket is only used for data push, it is sometimes still useful to support some bidirectional exchanges on the WebSocket, for example to allow the client to control what data to listen to.

3) Hmm, I think the only WebSocket demos we have are backend only.

4) When WebSocket-over-HTTP mode is used, Pushpin translates the client session into a series of POST requests to the backend. While you're correct that the client WebSocket negotiation sends a GET, it is Pushpin that sends a POST, so the backend needs to be able to handle POSTs.

I'm not sure where you see the POST handling occurring in Headline's views.py for the WebSocket though, as it's hidden behind WebSocketContext. Basically, if `request.wscontext` is valid, then it means the django-grip middleware has received a POST from Pushpin and interpreted it.

I hope this all makes sense.

**Comment by LihengGong** [comment]
Thank you for the detailed explanation. That helps me a lot.
